name: 'webqsp'
data_folder: 'datasets/webqsp/full/'
train_data: 'train.json'
train_documents: 'documents.json'
dev_data: 'dev.json'
dev_documents: 'documents.json'
test_data: 'test.json'
test_documents: 'documents.json'

word2id: 'vocab.txt'
relation2id: 'relations.txt'
entity2id: 'entities.txt'
word_emb_file: "word_emb_100d.npy"
entity_emb_file: null
entity_kge_file: null
relation_emb_file: null
relation_kge_file: null

to_save_model: True
save_model_file: "model/webqsp_new/best_model_kb"
pred_file: "model/webqsp_new/pred_kb"
load_model_file: "model/webqsp_new/best_model_kb"
# load_model_file: null

# graph options
fact_dropout: 0.1
use_kb: True
use_doc: False

num_layer: 3
max_query_word: 10
max_document_word: 50

entity_dim: 50
word_dim: 100
kge_dim: 100
pagerank_lambda: 0.8
fact_scale: 3
use_inverse_relation: False

# optimization
num_epoch: 100
batch_size: 10
gradient_clip: 1
learning_rate: 0.001
lstm_dropout: 0.3
linear_dropout: 0.2
is_debug: False


